# Generated by Django 2.0.10 on 2019-02-15 07:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rideone', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.CharField(max_length=100)),
                ('fro', models.CharField(max_length=100)),
                ('contact_date', models.DateField(blank=True)),
                ('contact_time', models.TimeField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehicl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rideone.vehicle')),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='cont',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rideone.ride'),
        ),
        migrations.AddField(
            model_name='contact',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
